console.log(typeof null);        //Output- Object (null is treated as an object type)
console.log([] == false);        //Output- true (empty array is converted to false)
console.log("5" + 2)             //Output- 52 (String concatenation - if one side is a string, JS does string concatenation."5" + 2 → "52")
console.log("5" - 2);            //Output- 3 (Subtraction converts string to number)
console.log(Boolean(""));        //Output- false (is false Non-zero numbers are true)
console.log(Boolean("0"));       //Output- true (Non-empty string is true)
console.log(0 === -0);           //Output- true (0 is equal to -0)
console.log(NaN === NaN);        //Output- false (NaN is not equal to itself)
console.log(Number("10px"));     //Output- NaN (String with non-numeric characters cannot convert to a number)
console.log(1 + true + "2");     //Output- 22 (1 + true = 2, then "2" concatenates → "22")